from snakemake.utils import min_version
min_version("8.0")

import os

configfile: "../config/config.yaml"
SAMPLES, = glob_wildcards(os.path.join(config["reads"],config["fastq_names_1"]))

include: "rules/preprocessing.smk"
include: "rules/assembly.smk"
include: "rules/binning.smk"
include: "rules/refine_bins.smk"
include: "rules/coverm.smk"
include: "rules/prophage_mags.smk"
include: "rules/prophage_unbinned.smk"
include: "rules/taxonomy.smk"
include: "rules/phages.smk"
include: "rules/reporting.smk"

def get_final_outputs():
    """Determine which outputs to generate based on configuration"""
    outputs = [
        expand(os.path.join(config["outdir"], "{sample}", "phage_analysis", "done"), sample = SAMPLES),
        os.path.join(config["outdir"], "pipeline_summary_report.html"),
        os.path.join(config["outdir"], "combined_prophage_table_all_samples.tsv")
    ]

    # Optionally add comparison outputs if requested
    if config.get("run_genomad_comparison", False):
        outputs.append(expand(os.path.join(config["outdir"], "{sample}", "phage_analysis", "genomad_comparison_report.txt"), sample = SAMPLES))

    return outputs

rule all:
    input:
        get_final_outputs()
    default_target: True
