# slurm resource configuration
executor: slurm
#executor: cluster-generic
#cluster-generic-submit-cmd: "sbatch"

# Resources to use if not otherwise specified    
default-resources:
  - mem_mb=16000
  - runtime=1440
  - cores=24
  - slurm_account=sahlab

jobs: 40
latency-wait: 60 
use-conda: True
conda-prefix: /ref/sahlab/software/miniforge3/envs/smk_envs_prophage_pipeline
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
#restart-times: 1

set-resources:
    host_removal:
        mem: 50G
        cpus_per_task: 24
    binning_prep:
        mem: 32G
        cpus_per_task: 24
    megahit:
        mem: 32G
        cpus_per_task: 24
        time: 180 
    genomad:
        mem: 50G
    checkm:
        mem: 50G
    mmseqs_taxonomy:
        mem: 700G
    coverm_mapping:
        mem: 50G
    checkv:
        mem: 50G
    gtdbtk_classify_bins:
        mem: 200G
        cpus_per_task: 24
